import type { Metadata } from "next";

import { Poppins } from "next/font/google";

import "../../globals.css";
import { Header } from "../layout/header";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased dark`}
        style={{ fontFamily: "var(--font-poppins)" }}
        suppressHydrationWarning
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
